version: 0.2

env:
  git-credential-helper: yes
  secrets-manager:
    DOCKERHUB_USERNAME: "prod/docker/login:docker-username"
    DOCKERHUB_PASSWORD: "prod/docker/login:docker-passwd"

phases:
  install:
    commands:
      - apt-key adv --refresh-keys --keyserver keyserver.ubuntu.com
      - apt-get update && apt-get -y install python3-pip jq
      - pip3 install --upgrade awscli
      - pip3 install boto3 botocore requests semantic_version
      - echo "Pulling SHARED_ENV from Secrets Manager"
      - echo "$DOCKERHUB_PASSWORD" | docker login --username "$DOCKERHUB_USERNAME" --password-stdin


  pre_build:
    commands:
      - sudo mkdir /usr/local/awscliv2
      - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      - unzip -q awscliv2.zip
      - |
        sudo ./aws/install --bin-dir /usr/local/bin --install-dir /usr/local/awscliv2 --update
      - export PATH="/usr/local/bin:$PATH"
      - aws --version
      - node --version
      - echo "check that the aws cli is installed"
  
  build:
    commands: 
      - echo "checking github repo"
      - pwd
      - echo "automatic build kicked off yet?"
      - echo $CODEBUILD_INITIATOR
      - export S_NAME=$(aws codebuild batch-get-builds --ids $CODEBUILD_BUILD_ID | jq -r '.builds[] | {serviceRole}' | jq -r .'serviceRole')
      - echo $S_NAME
      - ls -alh 



